package com.example.demo.utils;

public class Enumerators{
    public enum UserError{
        MISSING_USERNAME, MISSING_EMAIL, MISSING_PASSWORD,
        DUPLICATE_EMAIL, DUPLICATE_USERNAME, NO_ERROR,
        GENERIC_ERROR,USER_NOT_FOUND
    }
    public enum InteractionError {
        NO_ERROR, MISSING_REVIEW, MISSING_RATING, MISSING_AUTHOR, MISSING_USER_ID, MISSING_RECIPE_ID, INVALID_RATING, RECIPE_NOT_FOUND, USER_NOT_FOUND, GENERIC_ERROR,
        INTERACTION_NOT_FOUND,
        INVALID_FIELD,
    }
    public enum RecipeError{
        MISSING_NAME, MISSING_TIME, RECIPE_NOT_FOUND, NO_ERROR, GENERIC_ERROR
    }
}
